#!/usr/bin/env bash

# General
alias ll="ls -lh"
alias la="ls -A"
alias lz="ls -lZ"
alias ld="ls -ld"
alias l1="ls -1"
alias lla="ls -la"
alias lls="ls -laZ"

# Ansible
alias apb="ansible-playbook"
alias adoc="ansible-doc"
 
# Python
alias python="/usr/bin/env python3"
alias py="/usr/bin/env python3"
alias pip="/usr/bin/env python3 -m pip"
  
