#!/usr/bin/env bash

# Git
gitm() {
    git add -A
    git commit -m "$1"
    git push
}

manhtml() {
  query="$1"
  man -Thtml "$query" > "${query}.html" 2> /dev/null
  if [[ -d /srv/www/man ]]; then
    letter=${query:0:1}
    mv "$query" "/srv/www/man/${letter^^}"
  fi
}
