" Core
syntax on
colorscheme industry
set encoding=utf-8
set number
set numberwidth=1

" Defaults
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" Python
augroup ft_python
  autocmd!
  autocmd FileType python setlocal expandtab tabstop=4 softtabstop=4 shiftwidth=4
augroup END

" C & C++
augroup ft_c
  autocmd!
  autocmd FileType c,cpp setlocal expandtab tabstop=4 softtabstop=4 shiftwidth=4
  autocmd FileType c,cpp setlocal cindent
augroup END

" Bash, YAML, HTML, CSS 
augroup ft_others
  autocmd!
  autocmd FileType sh,bash setlocal expandtab tabstop=2 softtabstop=2 shiftwidth=2
augroup END
